// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  layout: string;
  root: string;
  txtContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
